params = struct( ...
  'in1', [1 2], ...
  'in2', [3 4], ...
  'in3', [5 6]);
varsToStore = {'out1', 'out2', 'out3'};

resultsJOBNUM = sweep('pacesweepex_script', params, ...
  'varsToStore', varsToStore, 'nTrials', 5, ...
  'jobNum', JOBNUM, 'totalJobs', TOTALJOBS);

save('resultsJOBNUM.mat','resultsJOBNUM');